version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3001:3001
    environment:
        - CONNECTION_STRING=mongodb+srv://AcroChargeDB:AcroChargeDB@cluster0.zzrsm.mongodb.net/AcroCharge
  mongo:
    image: mongo
    ports:
    - 27018:27017
    volumes:
    - mongodb:/data/db
volumes:
    mongodb: